// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASLMsj-yuEwvBP-1IYm77fIior_RW7ICc',
    appId: '1:841840819943:web:e3b2fcddc63db8cfc26c42',
    messagingSenderId: '841840819943',
    projectId: 'savour-26402',
    authDomain: 'savour-26402.firebaseapp.com',
    storageBucket: 'savour-26402.firebasestorage.app',
    measurementId: 'G-XYZ93EDYXF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACwuzyGHb6cjnF5w2Yt3mBipHYUTMdnxU',
    appId: '1:841840819943:android:f34b174a0f654eecc26c42',
    messagingSenderId: '841840819943',
    projectId: 'savour-26402',
    storageBucket: 'savour-26402.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQ3hdNx3JvhEWcH46ZDrYcYSvwLpwElGY',
    appId: '1:841840819943:ios:63ea42040bcc5ce7c26c42',
    messagingSenderId: '841840819943',
    projectId: 'savour-26402',
    storageBucket: 'savour-26402.firebasestorage.app',
    iosBundleId: 'com.example.savour',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQ3hdNx3JvhEWcH46ZDrYcYSvwLpwElGY',
    appId: '1:841840819943:ios:63ea42040bcc5ce7c26c42',
    messagingSenderId: '841840819943',
    projectId: 'savour-26402',
    storageBucket: 'savour-26402.firebasestorage.app',
    iosBundleId: 'com.example.savour',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyASLMsj-yuEwvBP-1IYm77fIior_RW7ICc',
    appId: '1:841840819943:web:cae9345cbdee8cfdc26c42',
    messagingSenderId: '841840819943',
    projectId: 'savour-26402',
    authDomain: 'savour-26402.firebaseapp.com',
    storageBucket: 'savour-26402.firebasestorage.app',
    measurementId: 'G-R6X6KSD4P2',
  );
}
